version: "3.8"

services:
  app:
    image: multi-stage-app:${BRANCH_NAME}
    container_name: app_${BRANCH_NAME}
    build:
      context: ./server
    ports:
      - "3000:3000"
    environment:
      - BRANCH_NAME=${BRANCH_NAME}
    restart: always
