name: Branch Based Docker Deployment

on:
  push:
    branches:
      - staging
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'main' && 'production' || 'staging' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Decide environment
        run: |
          if [ "${{ github.ref_name }}" = "staging" ]; then
            echo "HOST=${{ secrets.STAGING_EC2 }}" >> $GITHUB_ENV
            echo "BRANCH_NAME=staging" >> $GITHUB_ENV
          else
            echo "HOST=${{ secrets.PROD_EC2 }}" >> $GITHUB_ENV
            echo "BRANCH_NAME=main" >> $GITHUB_ENV
          fi

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan $HOST >> ~/.ssh/known_hosts

      - name: Deploy using Docker Compose
        run: |
          ssh ubuntu@$HOST << EOF
            cd Multi_Stage_Deployment

            git fetch origin
            git checkout $BRANCH_NAME
            git pull origin $BRANCH_NAME

            export BRANCH_NAME=$BRANCH_NAME

            docker-compose down
            docker-compose up -d --build
          EOF